### ISSUE TITLE
Ember Mug - Connectivity & How to get MAC ID for Mug?

### ISSUE THREAD

**Issue by fireheadman** [sopelj/hass-ember-mug-component#3]
Could you please give a snippet/info on how to get the MAC ID for the mug?
I personally use an iOS device, so maybe include for both Android and iOS.

Thanks

**Comment by fireheadman** [comment]
update:  was able to power on a galaxy s5 and install the ember app, pair the mug to it....  from there I was able to get the MAC from the bluetooth settings.

still unsure how a person without an android device would be able to get this info as the iOS native bluetooth app doesn't disclose this info.   maybe there is a 3rd party bluetooth scanner that can show this?


next step was to insert a bluetooth dongle into my HA server and reboot it, then added the ember.yaml to my integrations.

**Comment by fireheadman** [comment]
Looks like this is all I get now...
2022-01-04 12:37:37 INFO (MainThread) [homeassistant.setup] Setting up ember_mug
2022-01-04 12:37:37 INFO (MainThread) [homeassistant.setup] Setup of domain ember_mug took 0.0 seconds

But when I search the entities, nothing is to be found.

```
bash-5.1# cat ember.yaml
---
#
#  Ember Mug
#
ember_mug:
  mac: C5:B4:F7:XX:XX:XX  # Replace with your Mug's MAC address
  name: "Ember Mug"  # Optional Name
  temperature_unit: "F"  # Optional: Default [C]
```

**Comment by sopelj** [comment]
Yeah, I don't have an iOS device to test, but yeah it looks like Apple decided to hide it from iOS 12+.
So an android phone or desktop computer with bluetooth is currently the only way to obtain the MAC address.

I've been playing with config flow in home assistant (configuration via the UI) and that should allow me to either auto discover the device or at least list them in the UI. I just haven't had time to do it yet.

If you have the `Terminal/SSH` addon installed you can go into the console and use `bluetoothctl` and `scan on` to list nearby devices. You can find it there quickly.

That's weird. Do you have any other messages later? That just means the integration was loaded. 
You can specifically enable debug logs for this integration in your config if you want. That might help get a clearer error.

```yaml
logger:
  default: error
  logs:
    custom_components.ember_mug: debug
    custom_components.ember_mug.mug: debug
    custom_components.ember_mug.mug.api: debug
```
