### ISSUE TITLE
Feature request: predefined temperatures like in the Ember mobile app

### ISSUE THREAD

**Issue by ArtBIT** [sopelj/hass-ember-mug-component#45]
* Home Assistant Version (eg. 2023.11):
* Ember Mug Component Version (eg. 0.8.0):
* Which device(s) are you using for Bluetooth: ESPHome Proxy

### Description

I would like to be able to quickly select temperature from a predefined list of temperatures like in the Ember mobile app.

### What I Did

I've managed to achieve this by adding an input_select:
```
input_select:
  target_temperature:
    name: Ember Mug Target Temperature
    options:
      - Latte - 55⁰C
      - Cappuccino - 56⁰C
      - Coffee - 57⁰C
      - Black Tea - 58.5⁰C
      - Green Tea - 59⁰C
    initial: Black Tea - 58.5⁰C
    icon: mdi:tea
```

And an automation:
```
automation:
  - id: mug_target_temperature_changed
    alias: Mug Target Temperature Changed
    trigger:
      platform: state
      entity_id: input_select.target_temperature
    action:
      service: number.set_value
      data:
        value: "{{ states('input_select.target_temperature') | regex_replace(find='[^0-9.]', replace='', ignorecase=False) }}"
      target:
        entity_id: number.ember_mug_target_temp
```

Even though this custom component is already amazing (and I thank you for making it), this would make it even more awesome imho.
