### ISSUE TITLE
Bug: cant connect when proxy updated to ESPHome 2025.6.0

### ISSUE THREAD

**Issue by Zeronozero** [sopelj/hass-ember-mug-component#78]
### Home Assistant Version

2025.6.1

### Ember Mug Integration Version

1.3.0 b2

### What device(s) are you using?

Mug

### Which device(s) are you using for Bluetooth?

Multiple ESPHome Bluetooth Proxies

### Unexpected behaviour

I've just updated my bluetooth proxy to ESPHome from 2025.5.2 to 2025.6.0 and now my Ember Mug can't connect anymore.

### Expected behaviour

I know that it is this proxy update who give me bug because as soon as I downgrade, it is back and running perfectly

### Errors/Logs

```shell

```

**Comment by jitesh88** [comment]
> I'm also having this problem. I believe it's related to [ESPHome #7127](https://github.com/esphome/issues/issues/7127). There has been a fix made that will be included in 2025.6.1, but you can [test it now](https://github.com/esphome/issues/issues/7127#issuecomment-2987094282) if you want. The fix is working for me.

How can i test it out before the 2025.6.1 release. i referred to the link you shared, but couldnt get it to work.
i currently use this in my yaml template for the esphome

```
external_components:
  - source:
      type: git
      url: https://github.com/muneeb1990/esphome
      ref: powerpal_ble
    components: [ powerpal_ble ]
```
